#!/bin/bash

files=(
	"0-isupper.o"
	"0-memset.o"
	"0-strcat.o"
	"1-isdigit.o"
	"1-memcpy.o"
	"1-strncat.o"
	"100-atoi.o"
	"2-strchr.o"
	"2-strlen.o"
	"2-strncpy.o"
	"3-islower.o"
	"3-puts.o"
	"3-strcmp.o"
	"3-strspn.o"
	"4-isalpha.o"
	"4-strpbrk.o"
	"5-strstr.o"
	"6-abs.o"
	"9-strcpy.o"
	"_putchar.o"
)

for file in "${files[@]}"
do
	file_path=$(find .. -type f -name "$file" -print -quit)

	if [[ -n "$file_path" ]]; then
		cp "$file_path" .
		echo "copied $file to the current directory"
	else
		echo "chould not find $file"
	fi
done
